# Generated by Django 5.2 on 2026-01-11 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_page", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="map_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="property_images/map_image/"
            ),
        ),
        migrations.CreateModel(
            name="NearbyLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("school", "School"),
                            ("hospital", "Hospital"),
                            ("bank", "Bank"),
                            ("mall", "Mall"),
                            ("transport", "Transportation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("distance", models.DecimalField(decimal_places=2, max_digits=5)),
                ("distance_unit", models.CharField(default="miles", max_length=10)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nearby_locations",
                        to="agent_page.property",
                    ),
                ),
            ],
        ),
    ]
