# Generated by Django 5.2 on 2026-01-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_page", "0002_property_map_image_nearbylocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nearbylocation",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("school", "School"),
                    ("hospital", "Hospital"),
                    ("bank", "Bank"),
                    ("mall", "Mall"),
                    ("transport", "Transportation"),
                    ("city", "City"),
                    ("airport", "Airport"),
                    ("park", "Park"),
                    ("beach", "Beach"),
                    ("museum", "Museum"),
                    ("zoo", "Zoo"),
                    ("gym", "Gym"),
                    ("supermarket", "Supermarket"),
                    ("restaurant", "Restaurant"),
                ],
                max_length=50,
            ),
        ),
    ]
