# Generated by Django 5.2 on 2026-01-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_page", "0003_alter_nearbylocation_location_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
