# Generated by Django 5.2 on 2026-02-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_page", "0005_propertyviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
